### ISSUE TITLE
send custom message to chat

### ISSUE THREAD

**Issue by lavanyasree-ch** [SnapEngage/mobilesdk-android#1]
Hi, i need to send a custom data to snap engage sdk chat page in react native. i am sending like a widget id. means sending like props but that is not working. how can we send the custom data to chat?

**Comment by fibanez79** [comment]
Hello,
Have you checked [https://developer.snapengage.com/#javascript-api](https://developer.snapengage.com/#javascript-api)? Here we explain how to set custom fields by using our JS API methods.

**Comment by mayorchyk** [comment]
Closing the issue due to inactivity.

**Comment by fibanez79** [comment]
Was? Francisco IbáñezSent from my mobile phoneT: +49 (0) 152 05439032On 30. May 2024, at 11:51, Kiryl Mayorchyk ***@***.***> wrote:﻿
Closing the issue due to inactivity.
